function onMessage(messageEvent){if(messageEvent.data["func"]=='close'){window.parent.jQuery("#frameContent").hide();window.parent.jQuery('#regpopFrame').hide();window.parent.jQuery('html').removeClass("wj-hide");}
if(messageEvent.data["func"]=='redirect'){window.parent.location=messageEvent.data["redirecturl"];}}
var windowProxy;window.onload=function(){windowProxy=new Porthole.WindowProxy('https://app.webinarjam.net/proxy.html','regpopFrame');windowProxy.addEventListener(onMessage);};jQuery(document).ready(function($){$(document).on("click","a, button",function()
{var titleValue=$(this).attr('title');if(titleValue!=""&&typeof titleValue!=="undefined")
{var addressValue=titleValue.split('_')[0];if(typeof page==='undefined'||typeof page==='object')
page='';if(addressValue=='regpopbox')
{var memberid=titleValue.split('_')[1];var webicode=titleValue.split('_')[2];var timezone=$("input[name=local_timezone]").val();if($.trim(addressValue)!=''&&$.trim(memberid)!=''&&$.trim(webicode)!='')
{var url="https://app.webinarjam.net/registerBox/"+memberid+"/"+webicode+"?page="+page+"&page_tag=formregistration&ts="+Date.now();if(typeof timezone==="string")
url=url.concat("&tz="+timezone);$("html").addClass("wj-hide");$("#frameContent").html("");var height=document.documentElement.scrollHeight;if(height<830)
height=830;var div1=$("<div>").attr("id","div-wj-1").css({"width":"100%","height":"100%","position":"relative"});var div2=$("<div>").attr("id","div-wj-2").css({"margin":"auto"});div1.append(div2);$("#frameContent").append(div1).removeAttr("style").css({"webkit-overflow-scrolling":"touch !important","overflow-y":"auto","top":0,"left":0,"background":"rgba(0,0,0,0.8)","position":"absolute","width":"100%","height":"100%","display":"none","z-index":2147483647,"min-height":height});$('<iframe>',{src:url,id:'regpopFrame',style:'display:none;',frameborder:0,name:'regpopFrame',scrolling:'yes'}).appendTo($("#div-wj-2"));$('#regpopFrame').hide();$('#regpopFrame').css('cssText','height:830px !important');$('#regpopFrame').css({'width':'100%','z-index':250});$("#regpopFrame").fadeIn("slow");$("#frameContent").fadeIn("slow");$('html, body').animate({scrollTop:0},'slow');}}}});});