-- MySQL Script generated by MySQL Workbench
-- Mon May 29 22:06:24 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm` DEFAULT CHARACTER SET latin1 ;
USE `crm` ;

-- -----------------------------------------------------
-- Table `crm`.`arquivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`arquivos` (
  `arquivo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `arquivo_nome` VARCHAR(50) NOT NULL,
  `arquivo_remetente` INT(55) NOT NULL,
  PRIMARY KEY (`arquivo_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`atendimento` (
  `mensagem_id` INT(100) NOT NULL AUTO_INCREMENT,
  `mensagem_remetente` VARCHAR(100) NOT NULL,
  `mensagem_mensagem` TEXT NOT NULL,
  `mensagem_data` VARCHAR(100) NOT NULL,
  `mensagem_arquivo` VARCHAR(80) NOT NULL,
  `mensagem_respondida` INT(2) NOT NULL DEFAULT '0',
  `mensagem_resposta` TEXT NOT NULL,
  `mensagem_data_resposta` DATE NOT NULL,
  PRIMARY KEY (`mensagem_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 87
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`cadastro_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`cadastro_aluno` (
  `aluno_id` INT(50) NOT NULL AUTO_INCREMENT,
  `aluno_nome` VARCHAR(50) NOT NULL,
  `aluno_sexo` VARCHAR(30) NOT NULL,
  `aluno_escola` TEXT NOT NULL,
  `aluno_cidade` VARCHAR(50) NOT NULL,
  `aluno_msn` VARCHAR(50) NOT NULL,
  `aluno_senha` VARCHAR(50) NOT NULL,
  `status` INT(2) NOT NULL DEFAULT '1',
  `aluno_pendente` INT(2) NOT NULL DEFAULT '0',
  `aluno_foto` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`aluno_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 103
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`cadastro_escola`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`cadastro_escola` (
  `cadastro_id` INT(20) NOT NULL AUTO_INCREMENT,
  `cadastro_nome` VARCHAR(60) NOT NULL,
  `cadastro_cidade` VARCHAR(60) NOT NULL,
  `cadastro_email` VARCHAR(60) NOT NULL,
  `cadastro_telefone` VARCHAR(30) NOT NULL,
  `cadastro_escola` TEXT NOT NULL,
  PRIMARY KEY (`cadastro_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`clientes` (
  `cliente_id` INT(99) NOT NULL AUTO_INCREMENT,
  `cliente_responsavel` VARCHAR(90) NOT NULL,
  `cliente_nome` VARCHAR(90) NOT NULL,
  `cliente_email` VARCHAR(90) NOT NULL,
  `cliente_skype` VARCHAR(90) NOT NULL,
  `cliente_tel_fixo` VARCHAR(90) NOT NULL,
  `cliente_tel_cel` VARCHAR(90) NOT NULL,
  `cliente_nasc` VARCHAR(30) NOT NULL,
  `cliente_endereco` TEXT NOT NULL,
  `cliente_complemento` VARCHAR(90) NOT NULL,
  `cliente_bairro` VARCHAR(90) NOT NULL,
  `cliente_cep` VARCHAR(20) NOT NULL,
  `cliente_origem` VARCHAR(90) NOT NULL,
  `cliente_cidade` VARCHAR(90) NOT NULL,
  `cliente_uf` VARCHAR(10) NOT NULL,
  `cliente_data` VARCHAR(30) NOT NULL,
  `cliente_historico_data` DATE NOT NULL,
  `cliente_ultimo_historico` TEXT NOT NULL,
  `cliente_data_mod` VARCHAR(20) NOT NULL,
  `cliente_atendente` VARCHAR(90) NOT NULL,
  `cliente_atendente_edita` VARCHAR(90) NOT NULL,
  `cliente_atendente_id` INT(2) NOT NULL,
  `cliente_atendente_edita_id` INT(2) NOT NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 68
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`columns_priv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`columns_priv` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Table_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Column_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Column_priv` SET('Select', 'Insert', 'Update', 'References') NOT NULL DEFAULT '',
  PRIMARY KEY (`Host`, `Db`, `User`, `Table_name`, `Column_name`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Column privileges';


-- -----------------------------------------------------
-- Table `crm`.`contador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`contador` (
  `visitas` INT(5) NOT NULL DEFAULT '0')
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`curriculo` (
  `curriculo_id` INT(10) NOT NULL AUTO_INCREMENT,
  `curriculo_nome` TEXT NOT NULL,
  `curriculo_email` TEXT NOT NULL,
  `curriculo_telefone` TEXT NOT NULL,
  `curriculo_arquivo` TEXT NOT NULL,
  PRIMARY KEY (`curriculo_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`db`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`db` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Select_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Insert_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Update_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Delete_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Drop_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Grant_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `References_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Index_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Alter_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_tmp_table_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Lock_tables_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_view_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Show_view_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_routine_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Alter_routine_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Execute_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  PRIMARY KEY (`Host`, `Db`, `User`),
  INDEX `User` (`User` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Database privileges';


-- -----------------------------------------------------
-- Table `crm`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`documentos` (
  `documento_id` INT(11) NOT NULL AUTO_INCREMENT,
  `documento_nome` VARCHAR(90) NOT NULL,
  `documento_cli_id` VARCHAR(90) NOT NULL,
  `documento_atendente_id` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`documento_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`func`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`func` (
  `name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `ret` TINYINT(1) NOT NULL DEFAULT '0',
  `dl` CHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `type` ENUM('function', 'aggregate') CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'User defined functions';


-- -----------------------------------------------------
-- Table `crm`.`help_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`help_category` (
  `help_category_id` SMALLINT(5) UNSIGNED NOT NULL,
  `name` CHAR(64) NOT NULL,
  `parent_category_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `url` CHAR(128) NOT NULL,
  PRIMARY KEY (`help_category_id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'help categories';


-- -----------------------------------------------------
-- Table `crm`.`help_keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`help_keyword` (
  `help_keyword_id` INT(10) UNSIGNED NOT NULL,
  `name` CHAR(64) NOT NULL,
  PRIMARY KEY (`help_keyword_id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'help keywords';


-- -----------------------------------------------------
-- Table `crm`.`help_relation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`help_relation` (
  `help_topic_id` INT(10) UNSIGNED NOT NULL,
  `help_keyword_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`help_keyword_id`, `help_topic_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'keyword-topic relation';


-- -----------------------------------------------------
-- Table `crm`.`help_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`help_topic` (
  `help_topic_id` INT(10) UNSIGNED NOT NULL,
  `name` CHAR(64) NOT NULL,
  `help_category_id` SMALLINT(5) UNSIGNED NOT NULL,
  `description` TEXT NOT NULL,
  `example` TEXT NOT NULL,
  `url` CHAR(128) NOT NULL,
  PRIMARY KEY (`help_topic_id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'help topics';


-- -----------------------------------------------------
-- Table `crm`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`historico` (
  `historico_id` INT(50) NOT NULL AUTO_INCREMENT,
  `historico_prospecto_id` VARCHAR(50) NOT NULL,
  `historico_mensagem` TEXT NOT NULL,
  `historico_data` DATE NOT NULL,
  `historico_hora` VARCHAR(90) NOT NULL,
  `historico_atendente` VARCHAR(90) NOT NULL,
  `historico_atendente_id` INT(2) NOT NULL,
  PRIMARY KEY (`historico_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 259
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`host` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Select_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Insert_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Update_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Delete_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Drop_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Grant_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `References_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Index_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Alter_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_tmp_table_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Lock_tables_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_view_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Show_view_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_routine_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Alter_routine_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Execute_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  PRIMARY KEY (`Host`, `Db`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Host privileges;  Merged with database privileges';


-- -----------------------------------------------------
-- Table `crm`.`lembretes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`lembretes` (
  `lembrete_id` INT(50) NOT NULL AUTO_INCREMENT,
  `lembrete_titulo` VARCHAR(50) NOT NULL,
  `lembrete_mensagem` TEXT NOT NULL,
  `lembrete_data_cadastro` DATE NOT NULL,
  `lembrete_data` DATE NOT NULL,
  `lembrete_hora` VARCHAR(90) NOT NULL,
  `lembrete_minuto` VARCHAR(90) NOT NULL,
  `lembrete_atendente` VARCHAR(90) NOT NULL,
  `lembrete_atendente_id` INT(2) NOT NULL,
  PRIMARY KEY (`lembrete_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 260
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`pesquisas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`pesquisas` (
  `pesquisa_id` INT(99) NOT NULL AUTO_INCREMENT,
  `pesquisa_data` VARCHAR(50) NOT NULL,
  `pesquisa_cli_id` INT(99) NOT NULL,
  `pesquisa_cli` VARCHAR(90) NOT NULL,
  `pesquisa_semana` VARCHAR(20) NOT NULL,
  `pesquisa_matriculas` INT(90) NOT NULL,
  `pesquisa_50matriculas` VARCHAR(10) NOT NULL,
  `pesquisa_oquefaltou` TEXT NOT NULL,
  `pesquisa_entrar_escolas` VARCHAR(50) NOT NULL,
  `pesquisa_obs_entrar_escolas` VARCHAR(90) NOT NULL,
  `pesquisa_semana_aproveitada` VARCHAR(10) NOT NULL,
  `pesquisa_matricula_pais` VARCHAR(10) NOT NULL,
  `pesquisa_matricula_pct` VARCHAR(10) NOT NULL,
  `pesquisa_projeto_inovador_cli` VARCHAR(10) NOT NULL,
  `pesquisa_projeto_inovador_alunos` VARCHAR(10) NOT NULL,
  `pesquisa_nota` VARCHAR(10) NOT NULL,
  `pesquisa_obs_gerente` TEXT NOT NULL,
  PRIMARY KEY (`pesquisa_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`proc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`proc` (
  `db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `name` CHAR(64) NOT NULL DEFAULT '',
  `type` ENUM('FUNCTION', 'PROCEDURE') NOT NULL,
  `specific_name` CHAR(64) NOT NULL DEFAULT '',
  `language` ENUM('SQL') NOT NULL DEFAULT 'SQL',
  `sql_data_access` ENUM('CONTAINS_SQL', 'NO_SQL', 'READS_SQL_DATA', 'MODIFIES_SQL_DATA') NOT NULL DEFAULT 'CONTAINS_SQL',
  `is_deterministic` ENUM('YES', 'NO') NOT NULL DEFAULT 'NO',
  `security_type` ENUM('INVOKER', 'DEFINER') NOT NULL DEFAULT 'DEFINER',
  `param_list` BLOB NOT NULL,
  `returns` CHAR(64) NOT NULL DEFAULT '',
  `body` LONGBLOB NOT NULL,
  `definer` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `modified` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `sql_mode` SET('REAL_AS_FLOAT', 'PIPES_AS_CONCAT', 'ANSI_QUOTES', 'IGNORE_SPACE', 'NOT_USED', 'ONLY_FULL_GROUP_BY', 'NO_UNSIGNED_SUBTRACTION', 'NO_DIR_IN_CREATE', 'POSTGRESQL', 'ORACLE', 'MSSQL', 'DB2', 'MAXDB', 'NO_KEY_OPTIONS', 'NO_TABLE_OPTIONS', 'NO_FIELD_OPTIONS', 'MYSQL323', 'MYSQL40', 'ANSI', 'NO_AUTO_VALUE_ON_ZERO', 'NO_BACKSLASH_ESCAPES', 'STRICT_TRANS_TABLES', 'STRICT_ALL_TABLES', 'NO_ZERO_IN_DATE', 'NO_ZERO_DATE', 'INVALID_DATES', 'ERROR_FOR_DIVISION_BY_ZERO', 'TRADITIONAL', 'NO_AUTO_CREATE_USER', 'HIGH_NOT_PRECEDENCE') NOT NULL DEFAULT '',
  `comment` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  PRIMARY KEY (`db`, `name`, `type`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Stored Procedures';


-- -----------------------------------------------------
-- Table `crm`.`procs_priv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`procs_priv` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Routine_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Routine_type` ENUM('FUNCTION', 'PROCEDURE') CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `Grantor` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Proc_priv` SET('Execute', 'Alter Routine', 'Grant') NOT NULL DEFAULT '',
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Host`, `Db`, `User`, `Routine_name`, `Routine_type`),
  INDEX `Grantor` (`Grantor` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Procedure privileges';


-- -----------------------------------------------------
-- Table `crm`.`professora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`professora` (
  `professora_id` INT(2) NOT NULL AUTO_INCREMENT,
  `professora_nome` VARCHAR(50) NOT NULL,
  `professora_foto` VARCHAR(50) NOT NULL,
  `professora_login` VARCHAR(60) NOT NULL,
  `professora_senha` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`professora_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`prospectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`prospectos` (
  `prospecto_id` INT(10) NOT NULL AUTO_INCREMENT,
  `prospecto_responsavel` VARCHAR(90) NOT NULL,
  `prospecto_nome` VARCHAR(60) NOT NULL,
  `prospecto_email` VARCHAR(60) NOT NULL,
  `prospecto_tel_fixo` VARCHAR(20) NOT NULL,
  `prospecto_tel_cel` VARCHAR(20) NOT NULL,
  `prospecto_origem` VARCHAR(50) NOT NULL,
  `prospecto_indicado` VARCHAR(90) NOT NULL,
  `prospecto_cidade` VARCHAR(100) NOT NULL,
  `prospecto_uf` VARCHAR(2) NOT NULL,
  `prospecto_historico_data` DATE NOT NULL,
  `prospecto_ultimo_historico` TEXT NOT NULL,
  `prospecto_data` VARCHAR(30) NOT NULL,
  `prospecto_data_mod` VARCHAR(15) NOT NULL,
  `ghost` VARCHAR(50) NOT NULL,
  `prospecto_atendente` VARCHAR(90) NOT NULL,
  `prospecto_atendente_edita` VARCHAR(90) NOT NULL,
  `prospecto_atendente_id` INT(2) NOT NULL,
  `prospecto_atendente_edita_id` INT(2) NOT NULL,
  `prospecto_clienteagora` INT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`prospecto_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 69
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`respostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`respostas` (
  `resposta_id` INT(255) NOT NULL AUTO_INCREMENT,
  `resposta_pergunta_id` INT(255) NOT NULL,
  `resposta_aluno_id` INT(255) NOT NULL,
  `resposta_professora` VARCHAR(50) NOT NULL,
  `resposta_mensagem` TEXT NOT NULL,
  `resposta_data` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`resposta_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`tables_priv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`tables_priv` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Db` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Table_name` CHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Grantor` CHAR(77) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Table_priv` SET('Select', 'Insert', 'Update', 'Delete', 'Create', 'Drop', 'Grant', 'References', 'Index', 'Alter', 'Create View', 'Show view') NOT NULL DEFAULT '',
  `Column_priv` SET('Select', 'Insert', 'Update', 'References') NOT NULL DEFAULT '',
  PRIMARY KEY (`Host`, `Db`, `User`, `Table_name`),
  INDEX `Grantor` (`Grantor` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Table privileges';


-- -----------------------------------------------------
-- Table `crm`.`time_zone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`time_zone` (
  `Time_zone_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Use_leap_seconds` ENUM('Y', 'N') NOT NULL DEFAULT 'N',
  PRIMARY KEY (`Time_zone_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zones';


-- -----------------------------------------------------
-- Table `crm`.`time_zone_leap_second`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`time_zone_leap_second` (
  `Transition_time` BIGINT(20) NOT NULL,
  `Correction` INT(11) NOT NULL,
  PRIMARY KEY (`Transition_time`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Leap seconds information for time zones';


-- -----------------------------------------------------
-- Table `crm`.`time_zone_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`time_zone_name` (
  `Name` CHAR(64) NOT NULL,
  `Time_zone_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zone names';


-- -----------------------------------------------------
-- Table `crm`.`time_zone_transition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`time_zone_transition` (
  `Time_zone_id` INT(10) UNSIGNED NOT NULL,
  `Transition_time` BIGINT(20) NOT NULL,
  `Transition_type_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Time_zone_id`, `Transition_time`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zone transitions';


-- -----------------------------------------------------
-- Table `crm`.`time_zone_transition_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`time_zone_transition_type` (
  `Time_zone_id` INT(10) UNSIGNED NOT NULL,
  `Transition_type_id` INT(10) UNSIGNED NOT NULL,
  `Offset` INT(11) NOT NULL DEFAULT '0',
  `Is_DST` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `Abbreviation` CHAR(8) NOT NULL DEFAULT '',
  PRIMARY KEY (`Time_zone_id`, `Transition_type_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = 'Time zone transition types';


-- -----------------------------------------------------
-- Table `crm`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`user` (
  `Host` CHAR(60) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `User` CHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL DEFAULT '',
  `Password` CHAR(41) CHARACTER SET 'latin1' COLLATE 'latin1_bin' NOT NULL DEFAULT '',
  `Select_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Insert_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Update_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Delete_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Drop_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Reload_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Shutdown_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Process_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `File_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Grant_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `References_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Index_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Alter_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Show_db_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Super_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_tmp_table_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Lock_tables_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Execute_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Repl_slave_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Repl_client_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_view_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Show_view_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_routine_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Alter_routine_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `Create_user_priv` ENUM('N', 'Y') CHARACTER SET 'utf8' NOT NULL DEFAULT 'N',
  `ssl_type` ENUM('', 'ANY', 'X509', 'SPECIFIED') CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `ssl_cipher` BLOB NOT NULL,
  `x509_issuer` BLOB NOT NULL,
  `x509_subject` BLOB NOT NULL,
  `max_questions` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `max_updates` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `max_connections` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `max_user_connections` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`Host`, `User`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Users and global privileges';


-- -----------------------------------------------------
-- Table `crm`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`usuarios` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL DEFAULT 'genesis123',
  `nivel` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `crm`.`Pacientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`Pacientes` (
  `idPacientes` INT NOT NULL,
  `nm_paciente` VARCHAR(45) NULL,
  PRIMARY KEY (`idPacientes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
